### ISSUE TITLE
Questions about the Evaluation on KITTI Dataset

### ISSUE THREAD

**Issue by uniBruce** [hzxie/GRNet#1]
HI, thx for the amazing work. I'd like to inquire about the evaluation process of the metric consistency. I have obtained a much larger value than the result in your paper. It seems that if one of the inputs of the consistency metric is the result generated from very sparse points, the consistency value can be higher than 10. So how did you process these very sparse frames, or did you conduct any preprocessing before evaluation?

**Comment by hzxie** [comment]
What is "consistency"? Do you mean the metric used in KITTI?

**Comment by uniBruce** [comment]
> What is "consistency"? Do you mean the metric used in KITTI?
> What do you mean "very sparse frames"?

Yes. The metric used in Kitti. I checked the kitti
Test set provided by PCN, and some frames may contain no more than 10 points for a car

**Comment by hzxie** [comment]
Yes. We follow the settings of PCN.
We use the 3D bounding box to normalize the input point cloud.

**Comment by hzxie** [comment]
See also: https://github.com/hzxie/GRNet/blob/master/utils/data_transforms.py#L225-L249

**Comment by hzxie** [comment]
Closed due to inactivity.
If you have questions, please reopen this issue.
