### ISSUE TITLE
gridding_loss is not applied during training?

### ISSUE THREAD

**Issue by wangyida** [hzxie/GRNet#10]
Thanks for your interesting work, I noticed that gridding_loss is not really included in the training stage in your script although it's claimed in your paper, so your model is only optimised with chamfer distance for both coarse and dense point cloud? did I miss some details in your codes?

**Comment by hzxie** [comment]
Hi @wangyida.
Please refer to issue #8.

**Comment by wangyida** [comment]
Thanks Ill check then
