### ISSUE TITLE
KeyError:'gtcloud'

### ISSUE THREAD

**Issue by RichardHansir** [hzxie/GRNet#12]
Hi,
when i run the python runner.py --test --weights=../GRNet-KITTI.pth, i got **KeyError:'gtcloud'** in /core/test.py 

 How to fix it? Thanks.

**Comment by hzxie** [comment]
You cannot `test` on KITTI because no ground truth is available.
Instead, you can generate the prediction of GRNet by using `inference`.

Try:

```
python runner.py --inference --weights=../GRNet-KITTI.pth
```
