### ISSUE TITLE
Mapping to the KITTI raw dataset

### ISSUE THREAD

**Issue by ShivamDuggal4** [hzxie/GRNet#13]
Hi @hzxie 

Thanks for the great work !!

Can you please share the mapping of your processed KITTI dataset to the KITTI RAW dataset.
Basically I want to know, which log/ city/ frame each object is coming from.

Thanks !!

**Comment by hzxie** [comment]
Please refer to the answer in the PCN repo: https://github.com/wentaoyuan/pcn/issues/45

**Comment by ShivamDuggal4** [comment]
Hi @hzxie 

Thanks a lot for the quick reply.
Your answer helped find the exact mapping here: https://github.com/wentaoyuan/pcn/tree/master/data
