### ISSUE TITLE
How to evaluate GRNet on Completion 3d Benchmark？

### ISSUE THREAD

**Issue by Jhcnsn** [hzxie/GRNet#15]
Hi,
Thanks for your great work，and I saw the great result of the GRNet on the Leaderboard of Completion 3d  Benchmark.

When I tried to evaluate GRNet on the completion 3d benchmark, I found some difficulties, such as the version of cuda and pytorch. Completion 3d benchmark uses cuda9.0 and pytorch0.4.0.

Could you please give me some advice ?

Thanks a lot!

**Comment by hzxie** [comment]
We don't rely on any code from the Completion3D benchmark.
If you want to inference on Completion3D, you can simply run:

```
python3 runner.py --inference --weights=/path/to/pretrained/model.pth
```

Meanwhile, please update the `__C.DATASET.TEST_DATASET` to `Completion3D` in `config.py`.

**Comment by Jhcnsn** [comment]
Thanks a lot for your reply！
