### ISSUE TITLE
bbox.txt  DataFormat 

### ISSUE THREAD

**Issue by liyangzhong** [hzxie/GRNet#16]
hello，I am a newer for deep learning. I want to know the bbox.txt data format, thank you a lot!

**Comment by hzxie** [comment]
Please refer to https://github.com/wentaoyuan/pcn/blob/master/test_kitti.py#L59-L71

**Comment by liyangzhong** [comment]
Thanks for your reply.
Now I have no orientation boundingbox like kitti format, but I use traditional clustering method to get a cluster of one car and normlized to [-1,1],how can I complete the cluster? I want to compute the orientation of the cluster by PCA,if it is not completed, the PCA result may be not right.
I try it by kitti.pth and shape.pth ,I found the cluser is densed but not be completed, can you give some advice for the thing,thanks a lot!

**Comment by wsw233** [comment]
> Thanks for your reply. Now I have no orientation boundingbox like kitti format, but I use traditional clustering method to get a cluster of one car and normlized to [-1,1],how can I complete the cluster? I want to compute the orientation of the cluster by PCA,if it is not completed, the PCA result may be not right. I try it by kitti.pth and shape.pth ,I found the cluser is densed but not be completed, can you give some advice for the thing,thanks a lot!

Hello,I had the same problem as you, did you solve it?
