### ISSUE TITLE
errors in Build PyTorch Extensions

### ISSUE THREAD

**Issue by zhangyanan0306** [hzxie/GRNet#2]
HI, thx for the amazing work.
But when I run : python setup.py install --user
errors occur as follows:

![QQ截图20200709154447](https://user-images.githubusercontent.com/49965736/87012926-78279200-c1fc-11ea-8ee1-667e2465bd9c.png)

This error may be caused by:    cubic_feature_sampling.cu>>>>>>>>>ptcloud.data_ptr<float>(), cubic_features.data_ptr<float>()

How can I solve this problem?

I USE PyTorch = 1.2.0, CUDA = 10.1 and GCC = 5.4

**Comment by hzxie** [comment]
Sorry, I cannot reproduce your problem.
Line 193-197 in cubic_feature_sampling.cu is shown as follows.

https://github.com/hzxie/GRNet/blob/71390d4563952aa6902427adfc4de05205cb06bd/extensions/cubic_feature_sampling/cubic_feature_sampling.cu#L193-L197

There are no so many ">" in this statement.

**Comment by hzxie** [comment]
Actually, I haven't tested it on PyTorch 1.2.
Maybe you can try it on PyTorch 1.5.

**Comment by zhangyanan0306** [comment]
> Actually, I haven't tested it on PyTorch 1.2.
> Maybe you can try it on PyTorch 1.5.

It's really the problem with the pytorch version. After switching to 1.5.1, my problem was solved. Thank you very much！
