### ISSUE TITLE
how to evaluate on KITTI dataset

### ISSUE THREAD

**Issue by sychen-sjtu** [hzxie/GRNet#20]
In your paper, there are two methods (Consistency, Uniformity) to evaluate the output point clouds from the net. But I haven't found those codes. Can you tell me where are the codes so I can evaluate the output point clouds?
  Thank you in advance.

**Comment by hzxie** [comment]
Sorry, I can't find the code to evaluate consistency and uniformity now.
The consistency can be implemented according to the description of our paper and PCN (Yuan et al., 3DV 2018).
The code for evaluating uniformity can be found in https://github.com/liruihui/PU-GAN.

**Comment by sychen-sjtu** [comment]
Thank you very much!

**Comment by hzxie** [comment]
The code for evaluating the uniformity is available [here](https://github.com/hzxie/GRNet/files/6243444/PU-GAN-Uniformity.tar.gz).

**Comment by sychen-sjtu** [comment]
Thank you very much!!!
