### ISSUE TITLE
How can I turn off these debug logs?

### ISSUE THREAD

**Issue by leonardozcm** [hzxie/GRNet#24]
hi @hzxie, thanks for your great contribution. When i'm training your model, i find these duplicated prints
```
Format = auto
Extension = pcd
Format = auto
Extension = pcd
Format = auto
Extension = pcd
Format = auto
Extension = pcd
Format = auto
Extension = pcd
```
I'm new with this, could you pls tell me how to turn it off?

**Comment by hzxie** [comment]
Try to use another version of open3d?
