### ISSUE TITLE
the problem in ruinng python setup.py install --user

### ISSUE THREAD

**Issue by Peter199709** [hzxie/GRNet#29]
hello, when I python setup.py installer -user,it has some errors.
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/boxing/impl/boxing.h:268:122: error: expansion pattern 'c10::impl::can_box<FirstArg>' contains no argument packs
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/boxing/impl/boxing.h:268:149: error: template argument 1 is invalid
/usr/local/lib/python3.6/dist-packaages/torch/include/c10/util/variant.h:2395:107: error: expansion pattern 'Arg&&' contains no argument packs
error: could not convert '0' from 'int' to 'torch::nn::functional::ConvFuncOptions<2ul>::padding_t {aka c10::variant<torch::ExpandingArray<2ul, long int>, torch::enumtype::kValid, torch::enumtype::kSame>}'
     const Conv2dFuncOptions& options = {}) {
/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/nn/functional/conv.h:161:13: 

error: could not convert 'torch::kLeakyReLU' from 'const torch::enumtype::kLeakyReLU' to 'torch::nn::init::NonlinearityType {aka c10::variant<torch::enumtype::kLinear, torch::enumtype::kConv1D, torch::enumtype::kConv2D, torch::enumtype::kConv3D, torch::enumtype::kConvTranspose1D, torch::enumtype::kConvTranspose2D, torch::enumtype::kConvTranspose3D, torch::enumtype::kSigmoid, torch::enumtype::kTanh, torch::enumtype::kReLU, torch::enumtype::kLeakyReLU>}'
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
How can I solve it?

**Comment by hzxie** [comment]
What's your PyTorch version?

**Comment by hzxie** [comment]
Closed due to inactivity.
