### ISSUE TITLE
How to know the id of the input point cloud

### ISSUE THREAD

**Issue by Andykwan-ccu** [hzxie/GRNet#33]
I am using the gridding function, but how do I know the id of the point cloud I input?

thanks!

**Comment by Andykwan-ccu** [comment]
The dataset I am using is shapenet

**Comment by hzxie** [comment]
You can set batch size to 1 and print the ID at the data loader loop,

**Comment by Andykwan-ccu** [comment]
> 

thank you

**Comment by Andykwan-ccu** [comment]
thank you
