### ISSUE TITLE
The correspondence between the coordinates of the input point cloud and the vertices coordinates

### ISSUE THREAD

**Issue by Andykwan-ccu** [hzxie/GRNet#34]
During gridding, the coordinates of the input point cloud are normalized to (-1,1), but the coordinates of the vertices are {(-32,-32,-32),...,(31,31 ,31)}(N=64), is the input point cloud between the coordinates of V={(-1,-1,-1),...(1,1,1)} ? doesn't this mean that there are very few w with a value?

**Comment by hzxie** [comment]
No, the coordinates are scaled to (-32, 31) during Gridding.
