### ISSUE TITLE
Question: Why the values of vertices are larger than 1?

### ISSUE THREAD

**Issue by Andykwan-ccu** [hzxie/GRNet#36]
I used the command to display the value of the grid, and observed that many values will be greater than 1, which is different from (2) in the paper, I think N (vi) is not divided to cause w to be greater than one, or am I  misunderstand about (2)  (I think its value will be between 0~1)?

**Comment by hzxie** [comment]
No. For each grid cell, the values of vertices should between 0 and 1.
However, the values of vertices are accumulated from its neighboring grid cells.

**Comment by Andykwan-ccu** [comment]
So the value of wi will be between 0 and 1 (N (vi) have been divided), and the values of vertices will add the wi of the same vertex, which makes the value greater than one, 
but I also observed that there are some **values greater than 8** Is this reasonable (a vertex will be adjacent to at most eight grid cells)

**Comment by Andykwan-ccu** [comment]
so values of vertices are not divided by N (vi).
If so how do I know the number of N(vi)?
thank you!

**Comment by hzxie** [comment]
You can know it according to its coordinates.
For example, N(vi) = 0 for (0, 0, 0) and N(vi) = 8 for (15, 15, 15)

**Comment by Andykwan-ccu** [comment]
- So the returned grid is not divided by N(vi) ?(which called the value of vertices)

- If I want to know the value of wi, in addition to knowing the neighbors of each vertex, is there a variable about wi that can be printed out in the program?

Thanks for your reply!

**Comment by hzxie** [comment]
No.
