### ISSUE TITLE
How to save the repaired point cloud？

### ISSUE THREAD

**Issue by dfg112d** [hzxie/GRNet#38]
Using the trained model, how to specify to repair a broken point cloud and save the repaired point cloud?

**Comment by hzxie** [comment]
Please describe your problem more specifically.

**Comment by dfg112d** [comment]
训练好的模型如何对它的修复效果进行测试，能不能想二维图像识别一样，输入一个待识别的图像，输出识别后的图像，输入一个残缺的点云，输出修复后的点云




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hzxie/GRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hzxie/GRNet] How to save the repaired point cloud？ (Issue #38)





 
Please describe your problem more specifically.

**Comment by hzxie** [comment]
We didn't provide the code **single file** inference.
Instead, you can use the `--inference` option for `runner.py` to generate completed point clouds given a data loader.
