### ISSUE TITLE
How to improve the speed when loading shapenet data?

### ISSUE THREAD

**Issue by Be997398715** [hzxie/GRNet#39]
![image](https://user-images.githubusercontent.com/40139193/174315514-40fcfa23-a71e-4282-b391-cd55937dc56d.png)
As image above, I test the loading time of read_pcd file ,  each file needs about 3~4s , is there any way to improve training process ?
Wish for your reply!

**Comment by hzxie** [comment]
The data is loaded in an asynchronous way. As you can see, the data time is 0, which means the bottleneck of the training process is not data loading.

**Comment by Be997398715** [comment]
actactually it is asynchronous，but each minibatch data need to load(here  batchsize=32). And I found the minibatch data havent been ready for  next training, which means each minibatch train needs at least 8 data, and each data file needs about 3s to read from IO function. I think this is the key peroblem. I hope for your reply.

**Comment by hzxie** [comment]
Please try to use more data loader workers.
