### ISSUE TITLE
Error in preprocessing the ShapeNet Dataset

### ISSUE THREAD

**Issue by zhangyanan0306** [hzxie/GRNet#4]
when I run : python lmdb_serializer.py /path/to/shapenet/valid.lmdb /path/to/output/shapenet/val
errors occur as follows:
![QQ截图20200709222717](https://user-images.githubusercontent.com/49965736/87052470-67ded980-c233-11ea-901c-936bd6baac16.png)
This error may be due to a module name conflict. I guess it's /utils/ io.py Conflicts with Python internal file naming.
How can I solve this problem?

**Comment by hzxie** [comment]
@zhangyanan0306 
Sorry, I cannot reproduce your error.
In addition, I didn't import io in `lmdb_serializer.py `.

**Comment by hzxie** [comment]
You need to install `lmdb` and `tensorpack` before running the script.

```
pip install lmdb tensorpack
```

**Comment by zhangyanan0306** [comment]
> You need to install `lmdb` and `tensorpack` before running the script.
> 
> ```
> pip install lmdb tensorpack
> ```
One of your files is named io.py ，in ‘/utils/ io.py .    Are you sure it works?  Does this name not conflict with the IO module in Python?
After rename io.py  another name, the IO error is no longer prompted.
But there is another error as follows:
![QQ截图20200710104629](https://user-images.githubusercontent.com/49965736/87110890-aeb3ea00-c29a-11ea-8896-3522075ecb56.png)

It seems that GLIBC_2.27 is not supported in Ubuntu server 16.04.
You're using 18.04? What can I do to make it work on my 16.04.

**Comment by hzxie** [comment]
Actually, I'm using Arch Linux.
Maybe you can try a lower version of open3d?
I'll upload a processed ShapeNet dataset on Google Drive later.

**Comment by hzxie** [comment]
> > You need to install `lmdb` and `tensorpack` before running the script.
> > ```
> > pip install lmdb tensorpack
> > ```
> 
> One of your files is named io.py ，in ‘/utils/ io.py . Are you sure it works? Does this name not conflict with the IO module in Python?
> After rename io.py another name, the IO error is no longer prompted.

But I didn't import IO in this file. Please tell me why `io.py` appears in the stack trace?

**Comment by zhangyanan0306** [comment]
> > One of your files is named io.py ，in ‘/utils/ io.py . Are you sure it works? Does this name not conflict with the IO module in Python?
> > After rename io.py another name, the IO error is no longer prompted.
> 
> But I didn't import IO in this file. Please tell me why `io.py` appears in the stack trace?

open3d.**io**.write_point_cloud(os.path.join(partial_output_folder, '%02d.pcd' % idx), p)
open3d.**io**.write_point_cloud(os.path.join(complete_output_folder, '%s.pcd' % model_id), p)

Is it caused here?
He mistakenly gave priority to finding  /utils/io.py？

**Comment by hzxie** [comment]
I don't think so.

**Comment by hzxie** [comment]
I don't think so.
Are you using VS Code or PyCharm?
Try to run it in the Terminal.

Please refer to 
- https://stackoverflow.com/questions/26569828/pycharm-py-initialize-cant-initialize-sys-standard-streams
- https://python-forum.io/Thread-Fatal-Python-error-init-sys-streams-can-t-initialize-sys-standard-streams-Attribute

**Comment by zhangyanan0306** [comment]
> I don't think so.

![QQ截图20200710112351](https://user-images.githubusercontent.com/49965736/87113010-e709f700-c29f-11ea-936b-07ab570674d7.png)
What could be the reason?

**Comment by hzxie** [comment]
You can now download the processed dataset from [here](https://gateway.infinitescript.com/?fileName=ShapeNetCompletion).

**Comment by zhangyanan0306** [comment]
> You can now download the processed dataset from [here](https://gateway.infinitescript.com/?fileName=ShapeNetCompletion).

 Thank you very much！
