### ISSUE TITLE
Running on win10

### ISSUE THREAD

**Issue by Ali-Rashidi** [hzxie/GRNet#44]
Hello
Thanks a lot for this great repo
I'm trying to run the pretrained model of your work on win10 but I get multiple errors.
I wanted to know if it's even possible to run it on win10 or my machine has problems.
Thanks

**Comment by hzxie** [comment]
I think the problem may cause by the following code

https://github.com/hzxie/GRNet/blob/406248a4d0a25f8591e092ae02b9661e7fbdd6d1/core/train.py#L51

Please change to:

```
 output_dir = os.path.join(cfg.DIR.OUT_PATH, '%s', datetime.now().isoformat().replace(":", "-")) 
```

Because Windows does not support `:` in file name.

**Comment by hzxie** [comment]
Please provide more information (e.g. error logs) if the above reply did not solve your problem.

**Comment by Ali-Rashidi** [comment]
Thanks for your fast response sir.
I'll try your solution and if it didn't solve the problem I'll ask again.
Good day
