### ISSUE TITLE
Unable to run on KITTI

### ISSUE THREAD

**Issue by S-kewen** [hzxie/GRNet#47]
I have everything working fine in the ShapeNet dataset, but if I switch to KITTI it doesn't work. I have followed the steps to install dependencies and modify config.py.

python3 runner.py --test --weights=/home/skewen/GRNet/GRNet-KITTI.pth

`Traceback (most recent call last):
  File "runner.py", line 76, in <module>
    main()
  File "runner.py", line 65, in main
    test_net(cfg)
  File "/home/skewen/GRNet/core/test.py", line 71, in test_net
    sparse_loss = chamfer_dist(sparse_ptcloud, data['gtcloud'])
KeyError: 'gtcloud'`

**Comment by hzxie** [comment]
The KITTI does not support `test` due to the GT is missing for the dataset.
You can generate the completed point clouds with the following command

```
python3 runner.py --inference --weights=/home/skewen/GRNet/GRNet-KITTI.pth

```
