### ISSUE TITLE
[Open3D WARNING] Read PCD failed: unable to open file

### ISSUE THREAD

**Issue by seobokyeong0314** [hzxie/GRNet#50]
hello, author. When i tried to python runner.py, there were several files in the dataset that couldn't be opened. I have the following code:

Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/04379243/c7872212279d59eb540291e94bc8ddc3/01.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/04256520/f67714d13805df294b3c42e318f3affc/07.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/04379243/c7872212279d59eb540291e94bc8ddc3.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/04256520/f67714d13805df294b3c42e318f3affc.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/04256520/5f5c4e66f07fc2695c0be177939e290/04.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/04256520/5f5c4e66f07fc2695c0be177939e290.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/02958343/81c52d54f9719736ce27281f3b76d1f5/03.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/02691156/e70bd95ab764bc1b3465be15e1aa6a0c/04.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/02958343/81c52d54f9719736ce27281f3b76d1f5.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/02691156/e70bd95ab764bc1b3465be15e1aa6a0c.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/04256520/11be630221243013c087ef7d7cf00301/01.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/04256520/11be630221243013c087ef7d7cf00301.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/02958343/3d681ed2a7eef0df28f46021c78a3723/06.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/02958343/3d681ed2a7eef0df28f46021c78a3723.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/04379243/d03256544371f1eafa6e1fd63f4a1c35/01.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/04379243/d03256544371f1eafa6e1fd63f4a1c35.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/03636649/1ce6fb24e634d5962a510b8f97c658e/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/04256520/48228cf2207c7af5892eaa162d1e35d/01.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/partial/02933112/9dcc7002210e6660824662341ce2b233/06.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/04256520/48228cf2207c7af5892eaa162d1e35d.pcd
 ... 

and

File "/home/rmclab1003/FaceSegmentation/GRNet/models/grnet.py", line 138, in forward
    sparse_cloud = self.point_sampling(sparse_cloud, partial_cloud)
  File "/home/rmclab1003/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rmclab1003/FaceSegmentation/GRNet/models/grnet.py", line 30, in forward
    rnd_idx = torch.cat([torch.randint(0, n_pts, (self.n_points, ))])
RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0

Do you happen to know why? please give me some pointers, thanks!

**Comment by hzxie** [comment]
Please double-check the path to the dataset files.
Specifically, please make sure that `/home/FaceSegmentation/GRNet/datasets/ShapeNet/ShapeNetCompletion/train/complete/04256520/48228cf2207c7af5892eaa162d1e35d.pcd` is on your file system.
