### ISSUE TITLE
error in 'pip install -r requirements.txt'

### ISSUE THREAD

**Issue by seobokyeong0314** [hzxie/GRNet#53]
**When I wrote this, this error came up.**

___
Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting easydict
  Downloading easydict-1.10.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... done
Collecting h5py
  Downloading h5py-3.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 30.9 MB/s eta 0:00:00
Collecting matplotlib==3.0.3
  Downloading matplotlib-3.0.3.tar.gz (36.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.6/36.6 MB 28.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-iys51m99/matplotlib_75d929524e954c3dba9e69af5af6bfc2/setup.py", line 225, in <module>
          msg = pkg.install_help_msg()
        File "/tmp/pip-install-iys51m99/matplotlib_75d929524e954c3dba9e69af5af6bfc2/setupext.py", line 650, in install_help_msg
          release = platform.linux_distribution()[0].lower()
      AttributeError: module 'platform' has no attribute 'linux_distribution'
      ============================================================================
      Edit setup.cfg to change the build options
      
      BUILDING MATPLOTLIB
                  matplotlib: yes [3.0.3]
                      python: yes [3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC
                              11.2.0]]
                    platform: yes [linux]
      
      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [version 1.24.2]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [The C/C++ header for libpng (png.h) could not
                              be found.  You may need to install the development
                              package.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]
      
      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]
      
      OPTIONAL BACKEND EXTENSIONS
                         agg: yes [installing]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                      macosx: no  [Mac OS-X only]
                   windowing: no  [Microsoft Windows only]
      
      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]
      
      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details._

**So, i searched for a solution. and then, I found 'pip install -r requirements.txt --use-deprecated=legacy-resolver'.
But it didn't work, and I got this error.** 

Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting easydict
  Using cached easydict-1.10.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... done
Collecting h5py
  Using cached h5py-3.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-t3yrupt7/matplotlib/setup.py", line 225, in <module>
          msg = pkg.install_help_msg()
        File "/tmp/pip-install-t3yrupt7/matplotlib/setupext.py", line 650, in install_help_msg
          release = platform.linux_distribution()[0].lower()
      AttributeError: module 'platform' has no attribute 'linux_distribution'
      ============================================================================
      Edit setup.cfg to change the build options
      
      BUILDING MATPLOTLIB
                  matplotlib: yes [3.0.3]
                      python: yes [3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC
                              11.2.0]]
                    platform: yes [linux]
      
      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [version 1.24.2]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [The C/C++ header for libpng (png.h) could not
                              be found.  You may need to install the development
                              package.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]
      
      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]
      
      OPTIONAL BACKEND EXTENSIONS
                         agg: yes [installing]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                      macosx: no  [Mac OS-X only]
                   windowing: no  [Microsoft Windows only]
      
      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]
      
      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> matplotlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**i tried 'pip install -r requirements.txt --use-deprecated=backtrack-on-build-failures' But, it didn't work, too.**
**How can i solve it? thank you!**

**Comment by hzxie** [comment]
Please refer to [this solution](https://stackoverflow.com/questions/58758447/how-to-fix-module-platform-has-no-attribute-linux-distribution-when-instal) on StackOverflow.
