### ISSUE TITLE
关于pcn数据集

### ISSUE THREAD

**Issue by huyanbi** [hzxie/GRNet#55]
非常冒昧的问一个问题，由于我想把pcn数据集处理成.h5格式，但是在使用和你的读取数据一样的方式
df = dataflow.LMDBSerializer.load('data/valid.lmdb', shuffle=False)
读取时会出现错误
_pickle.UnpicklingError: invalid load key, '\xdd'.
请问这大概是什么原因呢，您是否遇到过类似的问题

**Comment by hzxie** [comment]
Duplicated with #4

**Comment by hzxie** [comment]
The following threads may help
- https://github.com/learnables/learn2learn/issues/310
- https://forums.ankiweb.net/t/pickle-unpicklingerror-invalid-load-key-x00/23664
