### ISSUE TITLE
How do I run this with my own data and just infer?

### ISSUE THREAD

**Issue by TarunSrinivas23** [hzxie/GRNet#59]
Hey all,

I see that you have a custom dataloader for the solution, but I was curious how to use this network on my own data. For example, say I have a PCD which is already incomplete, I do not have the ground truth for this. I just want to run inference on this data. How would be the best way to progress using this network? Any help on this would be very much appreciated. Thank you for the contribution !!

**Comment by hzxie** [comment]
The scenario described bears similarity to the KITTI dataset, where GT data for the completed shape of cars is not available. To address this limitation, we utilize the ShapeNet cars dataset for training purposes. You can also employ a similar approach with your own dataset by following these instructions.

**Comment by TarunSrinivas23** [comment]
Hey, thanks for the update. I was more curious on how to use this repository to just test with my data. Because I think the pretrained ones should be good enough for my data. My expected way of work would then be to just input my incomplete pointcloud and  just get the result from the network as output pointclouds. Is that something that is included anywhere in the code ?

**Comment by hzxie** [comment]
I did not provide a specific script for your use case. 
However, you can prepare your data by following the same format as the KITTI dataset and utilize the KITTI dataloader for compatibility and ease of use. 

This approach will allow you to effectively handle your data in a manner similar to the KITTI dataset.
