### ISSUE TITLE
How to reproduce the experiment of shape completion on KITTI?

### ISSUE THREAD

**Issue by zhangyanan0306** [hzxie/GRNet#6]
To reproduce the experiment of shape completion on KITTI, we just need to update settings in config.py:

```python
# Dataset Options: Completion3D, ShapeNet, ShapeNetCars, KITTI
__C.DATASET.TRAIN_DATASET                        = 'ShapeNetCars'
__C.DATASET.TEST_DATASET                         = 'KITTI'
```

Then run  `python3 runner.py`.

Am I right?

By the way, how to save and visualize the completion results on KITTI as shown in your paper?

**Comment by hzxie** [comment]
Yes. The settings are correct.
You can use [kitti_object_vis](https://github.com/kuixu/kitti_object_vis) to visualize the results of KITTI.

**Comment by zhangyanan0306** [comment]
> Yes. The settings are correct.
> You can use [kitti_object_vis](https://github.com/kuixu/kitti_object_vis) to visualize the results of KITTI.


OK, thank you very much！

**Comment by zhangyanan0306** [comment]
> Yes. The settings are correct.
> You can use [kitti_object_vis](https://github.com/kuixu/kitti_object_vis) to visualize the results of KITTI.

![QQ截图20200714164905](https://user-images.githubusercontent.com/49965736/87405928-a89f6f80-c5f2-11ea-9af9-635cdb1b9d92.png)
I encountered the above error in the training process, do you know how to solve it?

**Comment by hzxie** [comment]
It seems that there is something wrong with your matplotlib.
What's the version of matplotlib?

**Comment by zhangyanan0306** [comment]
> It seems that there is something wrong with your matplotlib.
> What's the version of matplotlib? Try to use 3.0.3.

my matplotlib is 3.2.2

**Comment by zhangyanan0306** [comment]
> It seems that there is something wrong with your matplotlib.
> What's the version of matplotlib? Try to use 3.0.3.
 
3.0.3 works for me！Thank you very much！
