### ISSUE TITLE
memory leak in the training code

### ISSUE THREAD

**Issue by cckamiya** [hzxie/GRNet#61]
There is a memory leak in the training code of this grnet model, and my training memory of more than 800epoch can occupy about 40G.

**Comment by hzxie** [comment]
Sorry, I cannot reproduce your issue.
At the time I conducted this experiment, I only had TITAN Xp with 12GB memory. It is impossible to occupy 40 GB of memory.

**Comment by cckamiya** [comment]
> Sorry, I cannot reproduce your issue. At the time I conducted this experiment, I only had TITAN Xp with 12GB memory. It is impossible to occupy 40 GB of memory.

The training data I use is Completion3D.

**Comment by cckamiya** [comment]
The training data I use is Completion3D.

**Comment by cckamiya** [comment]
By the memory, I don't mean the graphics memory of the graphics card, but the memory of the computer.

**Comment by hzxie** [comment]
Throughout the training process, all operations are executed on CUDA. If there is indeed a memory leak issue, my suspicion is that it might be associated with PyTorch or other Python libraries.
