### ISSUE TITLE
How do I run this network with my own collected data?

### ISSUE THREAD

**Issue by mostafa501** [hzxie/GRNet#63]
Dear @hzxie, thank you for the excellent work, I have simple question, how do i run the network to complete my own collected partial data. I have a part of chair data (.pcd format) as attacehd, I just want to test it using shape net dataset.
may you help me how to use the network for augmenting my data?.
[data_cluster.zip](https://github.com/hzxie/GRNet/files/12707877/data_cluster.zip)

**Comment by hzxie** [comment]
You need to implement the data loader as following.

https://github.com/hzxie/GRNet/blob/31046f6c4910f7d770e69b6445bb85c8aa3fd0b7/utils/data_loaders.py#L244-L306
