### ISSUE TITLE
How to get partial pcd from original KITTI dataset

### ISSUE THREAD

**Issue by husnejahan** [hzxie/GRNet#64]
Hi,

If I want to use more classes from KITTI dataset, how can I generate partial pcd from original?

http://www.cvlibs.net/datasets/kitti/

**Comment by hzxie** [comment]
What does the "more classes" mean?

**Comment by husnejahan** [comment]
Hi,
Not only car, other classes.
Thanks.

**Comment by hzxie** [comment]
During inference on the KITTI dataset, the 3D bounding boxes are required as input to normal objects to the canonical poses. 
However, there are only cars, pedestrians, and cyclists have 3D bounding box annotations. But in ShapeNet, there are only 3D shapes for cars.

To conclude, you can not use other classes in KITTI.
