### ISSUE TITLE
Training Error: TypeError: Cannot handle this data type: (1, 1, 800), |u1

### ISSUE THREAD

**Issue by husnejahan** [hzxie/GRNet#65]
Hi,
During training with PCN dataset I am getting error as follows:

File "/GRNet/core/test.py", line 84, in test_net
    test_writer.add_image('Model%02d/SparseReconstruction' % model_idx, sparse_ptcloud_img, epoch_idx)
TypeError: Cannot handle this data type: (1, 1, 800), |u1

**Comment by hzxie** [comment]
Please provide more information. What's the shape of sparse_ptcloud_img.

**Comment by hzxie** [comment]
Closed due to inactivity.
