### ISSUE TITLE
Environmental configuration

### ISSUE THREAD

**Issue by tsyyyds** [hzxie/GRNet#69]
May the author provide the original version of Python, Cuda, and torch you are using for reference？
I am using the python=3.9，Cuda=11.3，torch=1.11.0
thank you！

**Comment by hzxie** [comment]
I cannot recall the exact environment since the work was completed 5 years ago. According to the README,

> PyTorch >= 1.4, CUDA >= 9.0, and GCC >= 4.9 are required.

At that time, I used PyTorch 1.4, CUDA 9.0, and Python 3.9. However, I don't believe newer versions will cause issues. If you encounter any problems, please provide the specific error logs.
